baseURL = "https://tiny-speck-of-dust.s3.us-east-2.amazonaws.com/"
languageCode = "en-us"
title = "A tiny speck of dust exploring space"
theme = "ananke"
staticDir = ["images"]

[cascade]
  banner = "static/images/black-hole.jpg"

[build]
  publish = "public"
  command = "hugo --gc --minify"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/sushmitha_d_rao"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://linkedin.com/in/sushmitha-drao-a70697120 "
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-purple"
  featured_image = "static/images/black-hole.jpg"
  recent_posts_number = 2
  # toc = true


[deployment]
  order = [".jpg$", ".gif$"]


[[deployment.targets]]
  name = "new-posts"
  URL = "s3://tiny-speck-of-dust/"
